### PR TITLE
Create dist bundle

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

This PR adds infrastructure for generating distribution bundles on releases and adjusts the release instructions to note that one should generate the dist bundles and check them in on releases.

Connects #25

### Notes

- `babel-polyfill` apparently can't be nested, so I change this back to use `transform-runtime` as Babel recommends for libraries
- to reduce the size of the bundles, I made `react` and `react-dom` into externals which are then loaded from the apps which use this. This works pretty seamlessly except that the `react-onclickoutside` dependency expects ReactDOM 16.x to work correctly now. This upgrade will have to happen in the apps this gets used in, though.

## Testing Instructions
- run `.scripts/cibuild` and verify that it outputs two bundles in the `dist` dir: one minified, one not. Output should look similar to: https://travis-ci.org/azavea/pwd-unitybar/builds/308162185
- check the testing instructions in the GARP/EPA STAR cognate PR.

### CODE REVIEW

**Comment by kellyi** [comment]
Once this is in I'll make a 0.1.0 tagged release.

**Comment by rajadain** [comment]
Taking a look now

**Comment by rajadain** [comment]
This looks really good. The only thing I've noticed is that if I pull down this branch and make no changes, and run `cibuild`, it produces a different build:

```fish
> git status
On branch ki/create-dist-bundle
Your branch is up to date with 'origin/ki/create-dist-bundle'.

nothing to commit, working tree clean

> kj cibuild

... (npm torture) ...

> git status
On branch ki/create-dist-bundle
Your branch is up to date with 'origin/ki/create-dist-bundle'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dist/pwd.unitybar.js
	modified:   dist/pwd.unitybar.min.js
	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

I suspect this may have to do with my node and npm versions.

```fish
> node --version; and npm --version
v8.9.1
5.5.1
```

Perhaps the next thing to tackle (after this card) is to make reproducible builds.

**Comment by rajadain** [comment]
Here's the diff if interesting: [pwd.unitybar.js.diff.txt](https://github.com/azavea/pwd-unitybar/files/1518744/pwd.unitybar.js.diff.txt)

**Comment by rajadain** [comment]
Looks like it's using a different version of webpack on mine than yours?

**Comment by kellyi** [comment]
Interesting. I'm using Node 9.2 or so. The package json file specifies using webpack 2.7.0 but the `npm run bundle` command here just uses `webpack`, so I wonder if that's using a globally installed version?

Let me update the command to `node_modules/.bin/webpack etc` and see if that changes things.

**Comment by rajadain** [comment]
Okay trying with this.

**Comment by kellyi** [comment]
87073b2 seems to fix it locally: the output after `cibuild` differed for me too prior to that change. Once you get this change can you try running:

`npm run bundle` and then `git diff` to ensure nothing's changed

after that, can you try:

`./scripts/cibuild` and then `git diff` and see if anything's changed?

If `bundle` works but `cibuild` doesn't it's probably related to node-sass somehow. If `npm run bundle` doesn't work, then it's a different problem.

**Comment by rajadain** [comment]
Okay let me try with this.

**Comment by kellyi** [comment]
Thanks!

**Comment by kellyi** [comment]
> Once this is in I'll make a 0.1.0 tagged release.

While doing this also re-enabled the option to build all branches on Travis; otherwise Travis wasn't set up to build any `release` branches it saw. There's probably a more granular way to do this but I don't think there's much harm in building every branch.

**Pull request merged**
