### PR TITLE
Add babel-polyfill as an external dependency

### PR DESCRIPTION
**Pull request by arottersman**
When imported in other applications the bar
needs access to polyfills for Symbol and
other es6 elements to support IE11.
Add this as an external dependency
like how we treat react.

Supplemental to https://github.com/azavea/pwd-garp/pull/306

### CODE REVIEW

**Comment by kellyi** [comment]
Going to test this out and I think it should work, but I'm wondering whether we should instead add `babel-runtime` to this now and have the webpack.prod config run the code through that?

https://babeljs.io/docs/plugins/transform-runtime/

IIRC `babel-polyfill` is meant for applications and `babel-runtime` is more appropriate for libraries. The `runtime` docs have some discussion of using it to avoid polluting the global scope.

**Comment by arottersman** [comment]
Oh, yes, that's almost definitely what we want. Going to switch out for `babel-runtime` and `babel-plugin-transform-runtime`

**Comment by arottersman** [comment]
Fixup pushed with `babel-runtime` and no polyfill dependency.

**Comment by arottersman** [comment]
The build is failing because word `fixup` is in the commit message.

**Pull request merged**
