### PR TITLE
Enable hiding apps in app switcher

### LINKED ISSUE #81: Make Unity Bar Sticky in Demo Page
## Overview

The Unity Bar should be "sticky" in the Demo page, i.e. it should not be affected by scrolling. It should always be visible at the top. As if it were absolutely positioned.

### Is your feature request related to a problem? Please describe.

When testing the various Unity Bar options, one has to scroll down, which removes the Unity Bar from view. After changing the options, one has to scroll back up. This makes evaluating the effects of said options difficult.

### Describe the solution you'd like

The Unity Bar should always be visible in the demo page.

### Additional Context

This can either be done by custom styling the demo page, or adding a prop to the Unity Bar itself that does this. The latter would allow other client apps to achieve the same result, if the need should arise. But that is not a requirement of this issue. If the Demo page has it always visible, that is enough for this issue to be "done".

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

This PR enables hiding specific apps from the app switcher menu so that we can use the Unity Bar in applications which have been deployed while other applications have not been deployed.

First commit here fixes an issue via npm audit fix.

Connects #83 

### Demo

Screen Shot 2019-04-26 at 11 40 56 AM

### Notes

I intentionally did not attempt to change the width or of the App Switcher when not all of the apps are visible. If it becomes desirable to do that in the future -- for instance, if there's a long interval between the PV deployment and GARP deployment -- then we can handle it in another issue.

## Testing Instructions

- visit the netlify site
- toggle the apps in the app switcher and verify that they are displayed or hidden properly

### CODE REVIEW

**Comment by jwalgran** [comment]
Looking at this now.

**Comment by jwalgran** [comment]
Browsing https://5cc331cf1e070e000c24e9ba--staging-pwd-unitybar.netlify.com/

I can't scroll the page in Chrome, Safari, or Firefox.

In all screen captures I am scrolling up and down with my trackpad.

#### Chrome



#### Safari



#### Firefox

**Comment by kellyi** [comment]
Thanks for catching that. I'm just going to drop the demo app scroll changes related to #81 for now as they are not important for making the Unity Bar release. I pushed an amended commit and will update the testing instructions.

**Comment by kellyi** [comment]
Thanks!

**Pull request merged**
